name: 'Build Docs'

on:
  push:
    branches:
      - 'main'
      - 'master'
  schedule:
    # rebuild docs at 10 AM every Monday
    - cron:  '0 10 * * 1'

jobs:
  build_docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Show env
        run: 'env | sort -u'
      - name: Install Roswell
        env:
          LISP: ccl-bin
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          echo /home/runner/.roswell/bin >> $GITHUB_PATH
      - name: Create a wrapper to run CCL
        run: |
          mkdir -p /home/runner/.roswell/bin
          cp .github/workflows/ccl /home/runner/.roswell/bin/ccl
      - name: Build docs
        run: .github/workflows/build.ros
        env:
          # This token is automaticall added to the secrets
          # by GitHub. Read more here:
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
